//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesOmie
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL", ConfigurationName="ClientesOmie.ClientesCadastroSoap")]
    public interface ClientesCadastroSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLIncluirCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_status")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_status> IncluirClienteAsync(ClientesOmie.clientes_cadastro clientes_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLAlterarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_status")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_status> AlterarClienteAsync(ClientesOmie.clientes_cadastro clientes_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLExcluirCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_status")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_status> ExcluirClienteAsync(ClientesOmie.clientes_cadastro_chave clientes_cadastro_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLConsultarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_cadastro")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_cadastro> ConsultarClienteAsync(ClientesOmie.clientes_cadastro_chave clientes_cadastro_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLListarClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_listfull_response")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_listfull_response> ListarClientesAsync(ClientesOmie.clientes_list_request clientes_list_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLListarClientesResumido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_list_response")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_list_response> ListarClientesResumidoAsync(ClientesOmie.clientes_list_request clientes_list_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLIncluirClientesPorLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_lote_response")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_lote_response> IncluirClientesPorLoteAsync(ClientesOmie.clientes_lote_request clientes_lote_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLUpsertCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_status")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_status> UpsertClienteAsync(ClientesOmie.clientes_cadastro clientes_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLUpsertClientesPorLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_lote_response")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_lote_response> UpsertClientesPorLoteAsync(ClientesOmie.clientes_lote_request clientes_lote_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLUpsertClienteCpfCnpj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_status")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_status> UpsertClienteCpfCnpjAsync(ClientesOmie.clientes_cadastro clientes_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/clientes/?WSDLAssociarCodIntCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientes_cadastro_resumido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(clientesPorCodigo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(caracteristicas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tags))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="clientes_status")]
        System.Threading.Tasks.Task<ClientesOmie.clientes_status> AssociarCodIntClienteAsync(ClientesOmie.clientes_cadastro_chave clientes_cadastro_chave);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_cadastro
    {
        
        private string codigo_cliente_omieField;
        
        private string codigo_cliente_integracaoField;
        
        private string razao_socialField;
        
        private string cnpj_cpfField;
        
        private string nome_fantasiaField;
        
        private string telefone1_dddField;
        
        private string telefone1_numeroField;
        
        private string contatoField;
        
        private string enderecoField;
        
        private string endereco_numeroField;
        
        private string bairroField;
        
        private string complementoField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string cepField;
        
        private string codigo_paisField;
        
        private string separar_enderecoField;
        
        private string pesquisar_cepField;
        
        private string telefone2_dddField;
        
        private string telefone2_numeroField;
        
        private string fax_dddField;
        
        private string fax_numeroField;
        
        private string emailField;
        
        private string homepageField;
        
        private string inscricao_estadualField;
        
        private string inscricao_municipalField;
        
        private string inscricao_suframaField;
        
        private string optante_simples_nacionalField;
        
        private string tipo_atividadeField;
        
        private string cnaeField;
        
        private string produtor_ruralField;
        
        private string contribuinteField;
        
        private string observacaoField;
        
        private string obs_detalhadasField;
        
        private string recomendacao_atrasoField;
        
        private tags[] tagsField;
        
        private string pessoa_fisicaField;
        
        private string exteriorField;
        
        private string logradouroField;
        
        private string importado_apiField;
        
        private string bloqueadoField;
        
        private string cidade_ibgeField;
        
        private System.Nullable<decimal> valor_limite_creditoField;
        
        private bool valor_limite_creditoFieldSpecified;
        
        private string bloquear_faturamentoField;
        
        private recomendacoes recomendacoesField;
        
        private enderecoEntrega enderecoEntregaField;
        
        private string nifField;
        
        private string documento_exteriorField;
        
        private string inativoField;
        
        private dadosBancarios dadosBancariosField;
        
        private caracteristicas[] caracteristicasField;
        
        private string enviar_anexosField;
        
        private info infoField;
        
        private string bloquear_exclusaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_cliente_omie
        {
            get
            {
                return this.codigo_cliente_omieField;
            }
            set
            {
                this.codigo_cliente_omieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_cliente_integracao
        {
            get
            {
                return this.codigo_cliente_integracaoField;
            }
            set
            {
                this.codigo_cliente_integracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string razao_social
        {
            get
            {
                return this.razao_socialField;
            }
            set
            {
                this.razao_socialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnpj_cpf
        {
            get
            {
                return this.cnpj_cpfField;
            }
            set
            {
                this.cnpj_cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome_fantasia
        {
            get
            {
                return this.nome_fantasiaField;
            }
            set
            {
                this.nome_fantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone1_ddd
        {
            get
            {
                return this.telefone1_dddField;
            }
            set
            {
                this.telefone1_dddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone1_numero
        {
            get
            {
                return this.telefone1_numeroField;
            }
            set
            {
                this.telefone1_numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contato
        {
            get
            {
                return this.contatoField;
            }
            set
            {
                this.contatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endereco_numero
        {
            get
            {
                return this.endereco_numeroField;
            }
            set
            {
                this.endereco_numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string complemento
        {
            get
            {
                return this.complementoField;
            }
            set
            {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cidade
        {
            get
            {
                return this.cidadeField;
            }
            set
            {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cep
        {
            get
            {
                return this.cepField;
            }
            set
            {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_pais
        {
            get
            {
                return this.codigo_paisField;
            }
            set
            {
                this.codigo_paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string separar_endereco
        {
            get
            {
                return this.separar_enderecoField;
            }
            set
            {
                this.separar_enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pesquisar_cep
        {
            get
            {
                return this.pesquisar_cepField;
            }
            set
            {
                this.pesquisar_cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone2_ddd
        {
            get
            {
                return this.telefone2_dddField;
            }
            set
            {
                this.telefone2_dddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone2_numero
        {
            get
            {
                return this.telefone2_numeroField;
            }
            set
            {
                this.telefone2_numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fax_ddd
        {
            get
            {
                return this.fax_dddField;
            }
            set
            {
                this.fax_dddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fax_numero
        {
            get
            {
                return this.fax_numeroField;
            }
            set
            {
                this.fax_numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string homepage
        {
            get
            {
                return this.homepageField;
            }
            set
            {
                this.homepageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_estadual
        {
            get
            {
                return this.inscricao_estadualField;
            }
            set
            {
                this.inscricao_estadualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_municipal
        {
            get
            {
                return this.inscricao_municipalField;
            }
            set
            {
                this.inscricao_municipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_suframa
        {
            get
            {
                return this.inscricao_suframaField;
            }
            set
            {
                this.inscricao_suframaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string optante_simples_nacional
        {
            get
            {
                return this.optante_simples_nacionalField;
            }
            set
            {
                this.optante_simples_nacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipo_atividade
        {
            get
            {
                return this.tipo_atividadeField;
            }
            set
            {
                this.tipo_atividadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnae
        {
            get
            {
                return this.cnaeField;
            }
            set
            {
                this.cnaeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string produtor_rural
        {
            get
            {
                return this.produtor_ruralField;
            }
            set
            {
                this.produtor_ruralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contribuinte
        {
            get
            {
                return this.contribuinteField;
            }
            set
            {
                this.contribuinteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao
        {
            get
            {
                return this.observacaoField;
            }
            set
            {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string obs_detalhadas
        {
            get
            {
                return this.obs_detalhadasField;
            }
            set
            {
                this.obs_detalhadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recomendacao_atraso
        {
            get
            {
                return this.recomendacao_atrasoField;
            }
            set
            {
                this.recomendacao_atrasoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public tags[] tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pessoa_fisica
        {
            get
            {
                return this.pessoa_fisicaField;
            }
            set
            {
                this.pessoa_fisicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string exterior
        {
            get
            {
                return this.exteriorField;
            }
            set
            {
                this.exteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string logradouro
        {
            get
            {
                return this.logradouroField;
            }
            set
            {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string importado_api
        {
            get
            {
                return this.importado_apiField;
            }
            set
            {
                this.importado_apiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bloqueado
        {
            get
            {
                return this.bloqueadoField;
            }
            set
            {
                this.bloqueadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cidade_ibge
        {
            get
            {
                return this.cidade_ibgeField;
            }
            set
            {
                this.cidade_ibgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor_limite_credito
        {
            get
            {
                return this.valor_limite_creditoField;
            }
            set
            {
                this.valor_limite_creditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool valor_limite_creditoSpecified
        {
            get
            {
                return this.valor_limite_creditoFieldSpecified;
            }
            set
            {
                this.valor_limite_creditoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bloquear_faturamento
        {
            get
            {
                return this.bloquear_faturamentoField;
            }
            set
            {
                this.bloquear_faturamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public recomendacoes recomendacoes
        {
            get
            {
                return this.recomendacoesField;
            }
            set
            {
                this.recomendacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public enderecoEntrega enderecoEntrega
        {
            get
            {
                return this.enderecoEntregaField;
            }
            set
            {
                this.enderecoEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nif
        {
            get
            {
                return this.nifField;
            }
            set
            {
                this.nifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string documento_exterior
        {
            get
            {
                return this.documento_exteriorField;
            }
            set
            {
                this.documento_exteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo
        {
            get
            {
                return this.inativoField;
            }
            set
            {
                this.inativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public dadosBancarios dadosBancarios
        {
            get
            {
                return this.dadosBancariosField;
            }
            set
            {
                this.dadosBancariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public caracteristicas[] caracteristicas
        {
            get
            {
                return this.caracteristicasField;
            }
            set
            {
                this.caracteristicasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string enviar_anexos
        {
            get
            {
                return this.enviar_anexosField;
            }
            set
            {
                this.enviar_anexosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public info info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bloquear_exclusao
        {
            get
            {
                return this.bloquear_exclusaoField;
            }
            set
            {
                this.bloquear_exclusaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class tags
    {
        
        private string tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_lote_response
    {
        
        private string loteField;
        
        private string codigo_statusField;
        
        private string descricao_statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string lote
        {
            get
            {
                return this.loteField;
            }
            set
            {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_status
        {
            get
            {
                return this.codigo_statusField;
            }
            set
            {
                this.codigo_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao_status
        {
            get
            {
                return this.descricao_statusField;
            }
            set
            {
                this.descricao_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_lote_request
    {
        
        private string loteField;
        
        private clientes_cadastro[] clientes_cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string lote
        {
            get
            {
                return this.loteField;
            }
            set
            {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public clientes_cadastro[] clientes_cadastro
        {
            get
            {
                return this.clientes_cadastroField;
            }
            set
            {
                this.clientes_cadastroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_cadastro_resumido
    {
        
        private string codigo_clienteField;
        
        private string codigo_cliente_integracaoField;
        
        private string razao_socialField;
        
        private string nome_fantasiaField;
        
        private string cnpj_cpfField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_cliente
        {
            get
            {
                return this.codigo_clienteField;
            }
            set
            {
                this.codigo_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_cliente_integracao
        {
            get
            {
                return this.codigo_cliente_integracaoField;
            }
            set
            {
                this.codigo_cliente_integracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string razao_social
        {
            get
            {
                return this.razao_socialField;
            }
            set
            {
                this.razao_socialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome_fantasia
        {
            get
            {
                return this.nome_fantasiaField;
            }
            set
            {
                this.nome_fantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnpj_cpf
        {
            get
            {
                return this.cnpj_cpfField;
            }
            set
            {
                this.cnpj_cpfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_list_response
    {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private clientes_cadastro_resumido[] clientes_cadastro_resumidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas
        {
            get
            {
                return this.total_de_paginasField;
            }
            set
            {
                this.total_de_paginasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros
        {
            get
            {
                return this.registrosField;
            }
            set
            {
                this.registrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros
        {
            get
            {
                return this.total_de_registrosField;
            }
            set
            {
                this.total_de_registrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public clientes_cadastro_resumido[] clientes_cadastro_resumido
        {
            get
            {
                return this.clientes_cadastro_resumidoField;
            }
            set
            {
                this.clientes_cadastro_resumidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_listfull_response
    {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private clientes_cadastro[] clientes_cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas
        {
            get
            {
                return this.total_de_paginasField;
            }
            set
            {
                this.total_de_paginasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros
        {
            get
            {
                return this.registrosField;
            }
            set
            {
                this.registrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros
        {
            get
            {
                return this.total_de_registrosField;
            }
            set
            {
                this.total_de_registrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public clientes_cadastro[] clientes_cadastro
        {
            get
            {
                return this.clientes_cadastroField;
            }
            set
            {
                this.clientes_cadastroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientesPorCodigo
    {
        
        private string codigo_cliente_omieField;
        
        private string codigo_cliente_integracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_cliente_omie
        {
            get
            {
                return this.codigo_cliente_omieField;
            }
            set
            {
                this.codigo_cliente_omieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_cliente_integracao
        {
            get
            {
                return this.codigo_cliente_integracaoField;
            }
            set
            {
                this.codigo_cliente_integracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientesFiltro
    {
        
        private string codigo_cliente_omieField;
        
        private string codigo_cliente_integracaoField;
        
        private string cnpj_cpfField;
        
        private string razao_socialField;
        
        private string nome_fantasiaField;
        
        private string enderecoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private string cepField;
        
        private string contatoField;
        
        private string emailField;
        
        private string homepageField;
        
        private string inscricao_municipalField;
        
        private string inscricao_estadualField;
        
        private string inscricao_suframaField;
        
        private string pessoa_fisicaField;
        
        private string optante_simples_nacionalField;
        
        private string inativoField;
        
        private tags[] tagsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_cliente_omie
        {
            get
            {
                return this.codigo_cliente_omieField;
            }
            set
            {
                this.codigo_cliente_omieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_cliente_integracao
        {
            get
            {
                return this.codigo_cliente_integracaoField;
            }
            set
            {
                this.codigo_cliente_integracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnpj_cpf
        {
            get
            {
                return this.cnpj_cpfField;
            }
            set
            {
                this.cnpj_cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string razao_social
        {
            get
            {
                return this.razao_socialField;
            }
            set
            {
                this.razao_socialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome_fantasia
        {
            get
            {
                return this.nome_fantasiaField;
            }
            set
            {
                this.nome_fantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endereco
        {
            get
            {
                return this.enderecoField;
            }
            set
            {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bairro
        {
            get
            {
                return this.bairroField;
            }
            set
            {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cidade
        {
            get
            {
                return this.cidadeField;
            }
            set
            {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cep
        {
            get
            {
                return this.cepField;
            }
            set
            {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contato
        {
            get
            {
                return this.contatoField;
            }
            set
            {
                this.contatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string homepage
        {
            get
            {
                return this.homepageField;
            }
            set
            {
                this.homepageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_municipal
        {
            get
            {
                return this.inscricao_municipalField;
            }
            set
            {
                this.inscricao_municipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_estadual
        {
            get
            {
                return this.inscricao_estadualField;
            }
            set
            {
                this.inscricao_estadualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_suframa
        {
            get
            {
                return this.inscricao_suframaField;
            }
            set
            {
                this.inscricao_suframaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pessoa_fisica
        {
            get
            {
                return this.pessoa_fisicaField;
            }
            set
            {
                this.pessoa_fisicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string optante_simples_nacional
        {
            get
            {
                return this.optante_simples_nacionalField;
            }
            set
            {
                this.optante_simples_nacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo
        {
            get
            {
                return this.inativoField;
            }
            set
            {
                this.inativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public tags[] tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_list_request
    {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string apenas_importado_apiField;
        
        private string ordenar_porField;
        
        private string ordem_decrescenteField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_por_hora_deField;
        
        private string filtrar_por_hora_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        private clientesFiltro clientesFiltroField;
        
        private clientesPorCodigo[] clientesPorCodigoField;
        
        private string exibir_caracteristicasField;
        
        private string exibir_obsField;
        
        private string ordem_descrescenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina
        {
            get
            {
                return this.paginaField;
            }
            set
            {
                this.paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina
        {
            get
            {
                return this.registros_por_paginaField;
            }
            set
            {
                this.registros_por_paginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apenas_importado_api
        {
            get
            {
                return this.apenas_importado_apiField;
            }
            set
            {
                this.apenas_importado_apiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por
        {
            get
            {
                return this.ordenar_porField;
            }
            set
            {
                this.ordenar_porField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_decrescente
        {
            get
            {
                return this.ordem_decrescenteField;
            }
            set
            {
                this.ordem_decrescenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de
        {
            get
            {
                return this.filtrar_por_data_deField;
            }
            set
            {
                this.filtrar_por_data_deField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate
        {
            get
            {
                return this.filtrar_por_data_ateField;
            }
            set
            {
                this.filtrar_por_data_ateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_hora_de
        {
            get
            {
                return this.filtrar_por_hora_deField;
            }
            set
            {
                this.filtrar_por_hora_deField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_hora_ate
        {
            get
            {
                return this.filtrar_por_hora_ateField;
            }
            set
            {
                this.filtrar_por_hora_ateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao
        {
            get
            {
                return this.filtrar_apenas_inclusaoField;
            }
            set
            {
                this.filtrar_apenas_inclusaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao
        {
            get
            {
                return this.filtrar_apenas_alteracaoField;
            }
            set
            {
                this.filtrar_apenas_alteracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public clientesFiltro clientesFiltro
        {
            get
            {
                return this.clientesFiltroField;
            }
            set
            {
                this.clientesFiltroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public clientesPorCodigo[] clientesPorCodigo
        {
            get
            {
                return this.clientesPorCodigoField;
            }
            set
            {
                this.clientesPorCodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string exibir_caracteristicas
        {
            get
            {
                return this.exibir_caracteristicasField;
            }
            set
            {
                this.exibir_caracteristicasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string exibir_obs
        {
            get
            {
                return this.exibir_obsField;
            }
            set
            {
                this.exibir_obsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_descrescente
        {
            get
            {
                return this.ordem_descrescenteField;
            }
            set
            {
                this.ordem_descrescenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_cadastro_chave
    {
        
        private string codigo_cliente_omieField;
        
        private string codigo_cliente_integracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_cliente_omie
        {
            get
            {
                return this.codigo_cliente_omieField;
            }
            set
            {
                this.codigo_cliente_omieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_cliente_integracao
        {
            get
            {
                return this.codigo_cliente_integracaoField;
            }
            set
            {
                this.codigo_cliente_integracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class clientes_status
    {
        
        private string codigo_cliente_omieField;
        
        private string codigo_cliente_integracaoField;
        
        private string codigo_statusField;
        
        private string descricao_statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_cliente_omie
        {
            get
            {
                return this.codigo_cliente_omieField;
            }
            set
            {
                this.codigo_cliente_omieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_cliente_integracao
        {
            get
            {
                return this.codigo_cliente_integracaoField;
            }
            set
            {
                this.codigo_cliente_integracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_status
        {
            get
            {
                return this.codigo_statusField;
            }
            set
            {
                this.codigo_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao_status
        {
            get
            {
                return this.descricao_statusField;
            }
            set
            {
                this.descricao_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class info
    {
        
        private string dIncField;
        
        private string hIncField;
        
        private string uIncField;
        
        private string dAltField;
        
        private string hAltField;
        
        private string uAltField;
        
        private string cImpAPIField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dInc
        {
            get
            {
                return this.dIncField;
            }
            set
            {
                this.dIncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hInc
        {
            get
            {
                return this.hIncField;
            }
            set
            {
                this.hIncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uInc
        {
            get
            {
                return this.uIncField;
            }
            set
            {
                this.uIncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dAlt
        {
            get
            {
                return this.dAltField;
            }
            set
            {
                this.dAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hAlt
        {
            get
            {
                return this.hAltField;
            }
            set
            {
                this.hAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uAlt
        {
            get
            {
                return this.uAltField;
            }
            set
            {
                this.uAltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cImpAPI
        {
            get
            {
                return this.cImpAPIField;
            }
            set
            {
                this.cImpAPIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class caracteristicas
    {
        
        private string campoField;
        
        private string conteudoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string campo
        {
            get
            {
                return this.campoField;
            }
            set
            {
                this.campoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string conteudo
        {
            get
            {
                return this.conteudoField;
            }
            set
            {
                this.conteudoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class dadosBancarios
    {
        
        private string codigo_bancoField;
        
        private string agenciaField;
        
        private string conta_correnteField;
        
        private string doc_titularField;
        
        private string nome_titularField;
        
        private string transf_padraoField;
        
        private string cChavePixField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_banco
        {
            get
            {
                return this.codigo_bancoField;
            }
            set
            {
                this.codigo_bancoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string agencia
        {
            get
            {
                return this.agenciaField;
            }
            set
            {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string conta_corrente
        {
            get
            {
                return this.conta_correnteField;
            }
            set
            {
                this.conta_correnteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string doc_titular
        {
            get
            {
                return this.doc_titularField;
            }
            set
            {
                this.doc_titularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome_titular
        {
            get
            {
                return this.nome_titularField;
            }
            set
            {
                this.nome_titularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string transf_padrao
        {
            get
            {
                return this.transf_padraoField;
            }
            set
            {
                this.transf_padraoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cChavePix
        {
            get
            {
                return this.cChavePixField;
            }
            set
            {
                this.cChavePixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class enderecoEntrega
    {
        
        private string entRazaoSocialField;
        
        private string entCnpjCpfField;
        
        private string entEnderecoField;
        
        private string entNumeroField;
        
        private string entComplementoField;
        
        private string entBairroField;
        
        private string entCEPField;
        
        private string entEstadoField;
        
        private string entCidadeField;
        
        private string entSepararEnderecoField;
        
        private string entTelefoneField;
        
        private string entIEField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entRazaoSocial
        {
            get
            {
                return this.entRazaoSocialField;
            }
            set
            {
                this.entRazaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entCnpjCpf
        {
            get
            {
                return this.entCnpjCpfField;
            }
            set
            {
                this.entCnpjCpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entEndereco
        {
            get
            {
                return this.entEnderecoField;
            }
            set
            {
                this.entEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entNumero
        {
            get
            {
                return this.entNumeroField;
            }
            set
            {
                this.entNumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entComplemento
        {
            get
            {
                return this.entComplementoField;
            }
            set
            {
                this.entComplementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entBairro
        {
            get
            {
                return this.entBairroField;
            }
            set
            {
                this.entBairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entCEP
        {
            get
            {
                return this.entCEPField;
            }
            set
            {
                this.entCEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entEstado
        {
            get
            {
                return this.entEstadoField;
            }
            set
            {
                this.entEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entCidade
        {
            get
            {
                return this.entCidadeField;
            }
            set
            {
                this.entCidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entSepararEndereco
        {
            get
            {
                return this.entSepararEnderecoField;
            }
            set
            {
                this.entSepararEnderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entTelefone
        {
            get
            {
                return this.entTelefoneField;
            }
            set
            {
                this.entTelefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string entIE
        {
            get
            {
                return this.entIEField;
            }
            set
            {
                this.entIEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/clientes/?WSDL")]
    public partial class recomendacoes
    {
        
        private string numero_parcelasField;
        
        private string codigo_vendedorField;
        
        private string email_faturaField;
        
        private string gerar_boletosField;
        
        private string codigo_transportadoraField;
        
        private string tipo_assinanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numero_parcelas
        {
            get
            {
                return this.numero_parcelasField;
            }
            set
            {
                this.numero_parcelasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_vendedor
        {
            get
            {
                return this.codigo_vendedorField;
            }
            set
            {
                this.codigo_vendedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email_fatura
        {
            get
            {
                return this.email_faturaField;
            }
            set
            {
                this.email_faturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string gerar_boletos
        {
            get
            {
                return this.gerar_boletosField;
            }
            set
            {
                this.gerar_boletosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_transportadora
        {
            get
            {
                return this.codigo_transportadoraField;
            }
            set
            {
                this.codigo_transportadoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipo_assinante
        {
            get
            {
                return this.tipo_assinanteField;
            }
            set
            {
                this.tipo_assinanteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ClientesCadastroSoapChannel : ClientesOmie.ClientesCadastroSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ClientesCadastroSoapClient : System.ServiceModel.ClientBase<ClientesOmie.ClientesCadastroSoap>, ClientesOmie.ClientesCadastroSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClientesCadastroSoapClient() : 
                base(ClientesCadastroSoapClient.GetDefaultBinding(), ClientesCadastroSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ClientesCadastroSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesCadastroSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ClientesCadastroSoapClient.GetBindingForEndpoint(endpointConfiguration), ClientesCadastroSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesCadastroSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClientesCadastroSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesCadastroSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClientesCadastroSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientesCadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_status> IncluirClienteAsync(ClientesOmie.clientes_cadastro clientes_cadastro)
        {
            return base.Channel.IncluirClienteAsync(clientes_cadastro);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_status> AlterarClienteAsync(ClientesOmie.clientes_cadastro clientes_cadastro)
        {
            return base.Channel.AlterarClienteAsync(clientes_cadastro);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_status> ExcluirClienteAsync(ClientesOmie.clientes_cadastro_chave clientes_cadastro_chave)
        {
            return base.Channel.ExcluirClienteAsync(clientes_cadastro_chave);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_cadastro> ConsultarClienteAsync(ClientesOmie.clientes_cadastro_chave clientes_cadastro_chave)
        {
            return base.Channel.ConsultarClienteAsync(clientes_cadastro_chave);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_listfull_response> ListarClientesAsync(ClientesOmie.clientes_list_request clientes_list_request)
        {
            return base.Channel.ListarClientesAsync(clientes_list_request);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_list_response> ListarClientesResumidoAsync(ClientesOmie.clientes_list_request clientes_list_request)
        {
            return base.Channel.ListarClientesResumidoAsync(clientes_list_request);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_lote_response> IncluirClientesPorLoteAsync(ClientesOmie.clientes_lote_request clientes_lote_request)
        {
            return base.Channel.IncluirClientesPorLoteAsync(clientes_lote_request);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_status> UpsertClienteAsync(ClientesOmie.clientes_cadastro clientes_cadastro)
        {
            return base.Channel.UpsertClienteAsync(clientes_cadastro);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_lote_response> UpsertClientesPorLoteAsync(ClientesOmie.clientes_lote_request clientes_lote_request)
        {
            return base.Channel.UpsertClientesPorLoteAsync(clientes_lote_request);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_status> UpsertClienteCpfCnpjAsync(ClientesOmie.clientes_cadastro clientes_cadastro)
        {
            return base.Channel.UpsertClienteCpfCnpjAsync(clientes_cadastro);
        }
        
        public System.Threading.Tasks.Task<ClientesOmie.clientes_status> AssociarCodIntClienteAsync(ClientesOmie.clientes_cadastro_chave clientes_cadastro_chave)
        {
            return base.Channel.AssociarCodIntClienteAsync(clientes_cadastro_chave);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientesCadastroSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientesCadastroSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://app.omie.com.br/api/v1/geral/clientes/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClientesCadastroSoapClient.GetBindingForEndpoint(EndpointConfiguration.ClientesCadastroSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClientesCadastroSoapClient.GetEndpointAddress(EndpointConfiguration.ClientesCadastroSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            ClientesCadastroSoap,
        }
    }
}
